### ISSUE TITLE
[BUG] Additional software required on Linux

### ISSUE THREAD

**Issue by romilly** [facebookresearch/minihack#26]
## 🐛 Bug

I had to install additional software before nle would build on Linux 
Some requirements were obvious to me, some were not.

Here's what worked

```
conda create -n minihack python=3.8
conda activate minihack
sudo apt install cmake
sudo apt install build-essential
sudo apt install python3-dev
sudo apt install libbz2-dev
pip install minihack
# NB> I had previously run sudo apt install libpcre3-dev
# in order to install gym
```

## To Reproduce

run (without the additional dependencies)

```
conda create -n minihack python=3.8
conda activate minihack
pip install minihack
```

result;

Failed to build nle
ERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly
 
# Environment

Linux Mint 20.2
Python 3.8.12 
conda 4.10.3

**Comment by samvelyan** [comment]
Hi @romilly. Thanks for your contribution. In our instructions on how to install MiniHack, there is a Note regarding installing NLE on Ubuntu. We refer the users to [NLE installation instructions](https://github.com/facebookresearch/nle#installation) for this. I see that the dependencies you added yourself are already included in there. Perhaps this wasn't well highlighted in the README, apologies for that. 

Feel free to reopen in case you have any further issues.
