### ISSUE TITLE
[FEATURE] Simpler user experience when placing items

### ISSUE THREAD

**Issue by Aceticia** [facebookresearch/minihack#35]
## 🚀 Feature
A complete catalog of items that you can sample from, sorted by their type (e.g. weapon, edible...). This might be done by adapting the data from [this issue](https://github.com/NetHack/NetHack/issues/634#issue-1052811015). 
 

## Motivation
We can already find the meaning of all the commands and all placeable tiles, and a subset of edible items are also listed in the rewards manager file. But we don't yet have a catalog of all placeable items/edibles. 

## Pitch
This feature will make generation of map much easier and more complete. e.g, we might want to generate levels with different weapons and train agents to behave differently accordingly, or train them to behave identically regardless of what weapon is on the ground.

## Additional context
I'm new to the package and I'm happy to learn more about it. I looked and didn't find a similar feature. If there has already been ways of implementing this, can you shed some light on how to do this? Thank you.

**Comment by heiner** [comment]
I took a look at the issue in question; after [this PR](https://github.com/facebookresearch/nle/pull/292) one can produce names with Python code in NLE in the same way, e.g. like this: https://gist.github.com/c5117ed04851c50744779af81825c899
