### ISSUE TITLE
[FEATURE] Suggested MiniHack Editor Webpage tweaks

### ISSUE THREAD

**Issue by rockt** [facebookresearch/minihack#51]
## 🚀 Feature

Could we populate the level with a standard level that demonstrates the individual building blocks ([like the one used on the readme](https://raw.githubusercontent.com/facebookresearch/minihack/main/docs/imgs/level_editor.png))? Could we also have a "clear level" button to get to the empty level that is currently shown when calling https://minihack-editor.github.io/

**Comment by samvelyan** [comment]
CC @Bam4d

**Comment by samvelyan** [comment]
Solved in https://github.com/minihack-editor/minihack-editor.github.io/pull/1.
