### ISSUE TITLE
Windows user Error installing minihack with Docker

### ISSUE THREAD

**Issue by Robinaoko** [facebookresearch/minihack#52]
Hi, I'm trying to install minihack on windows. But after I follow the tutorial using Docker and do a pip install minihack, I get the following error：

ERROR: Failed building wheel for nle
ERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly

How can I solve this problem?

**Comment by Robinaoko** [comment]
I think my problem is that I haven't figured out how to use dockerfile. 
The link to the instructions installed in the picture is no longer valid.

![image](https://user-images.githubusercontent.com/68173679/167271368-0569026a-6e10-466f-b335-d2cd7ab9e6f7.png)

Could you please tell me how to use these dockerfiles in Windows? I would be very grateful.

**Comment by simiaolin** [comment]
Did you solve the problem?
