### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by simiaolin** [facebookresearch/minihack#80]
## 🚀 Windows support

There is limited documentation on how to install minihack on Windows. Why do I use a minihack docker image in windows? Why can't I directly do like what I do on macOS or ubuntu system?

**Comment by samvelyan** [comment]
Hi @simiaolin. MiniHack is based on and built on top of the [NetHack Learning Environment](https://github.com/facebookresearch/nle) which is built primarily for Linux/MacOS. For Windows, you'd need to use a Docker image, and the same goes for MiniHack.

**Comment by simiaolin** [comment]
I see. Thanks for clarifying it  : )
