### ISSUE TITLE
[BUG] TypeError: __init__() got an unexpected keyword argument 'archivefile'

### ISSUE THREAD

**Issue by EmmaHongW** [facebookresearch/minihack#81]
## To Reproduce

1. Run the Tutorial on Google Colab
2. Build an environment and try to print it

(https://github.com/facebookresearch/minihack/tree/main/minihack/tiles)/rendering.py
Executed line: render_des_file(des_file, n_images=1, full_screen=False)
Error message: TypeError: __init__() got an unexpected keyword argument 'archivefile'

## Expected behavior

 
Normally it should print out a picture of the environment

## Environment

 - MiniHack Version (e.g., 1.0): 0.1.5
 - NLE Version (e.g. 1.0): 0.9.0
 - PyTorch Version (e.g., 1.0): 0.23.0
 - OS (e.g., Linux): Mac OS
 - Python version: 3.9

## Temporary solution:
I redefined the function and deleted the "archivefile=None" from the function, then it worked.

**Comment by samvelyan** [comment]
Hi @EmmaHongW. Thanks for pointing this out. Indeed, the `archivefile` parameter has been removed in `NLE==0.9.0` version and needs to be removed here.

Given that you have already come up with the solution, would you want to submit a PR for resolving the issue?

**Comment by samvelyan** [comment]
Resolved in [this](https://github.com/facebookresearch/minihack/commit/58a3c958985e5a63f03b94cd6413fe565debe662) commit.
