### ISSUE TITLE
[FEATURE] Gymnasium support

### ISSUE THREAD

**Issue by TheEimer** [facebookresearch/minihack#92]
## 🚀 Feature

Upgrading from the (by now pretty old) gym version to gymnasium.

## Motivation

Better usability of MiniHack with standard training libraries like SB3.

## Pitch

Since gymnasium is becoming the default in more and more training libraries, it would be great to be able to use MiniHack in gymnasium. 

## Alternatives

-

## Additional context

I don't know exactly how much effort that would mean in MiniHack, but I upgraded a  package from gym to gymnasium with relatively small effort (for me it was mostly just changing the import, making sure the signature is updated and that the registration still does what it should). So hopefully this could be done fairly quickly.

**Comment by samvelyan** [comment]
Thanks for the request. Being based on [NLE](https://github.com/facebookresearch/nle), MiniHack can only support Gymnasium once NLE does. And it seems like there is already an enhancement request for this there: https://github.com/facebookresearch/nle/issues/357.

**Comment by leor-c** [comment]
It seems that future development of NLE is moving to https://github.com/heiner/nle ([source](https://github.com/StephenOman/nle/pull/2#issuecomment-2099247877)).
This new NLE repo already supports gymnasium.
