### ISSUE TITLE
[BUG] Outdated documentation

### ISSUE THREAD

**Issue by JupiLogy** [facebookresearch/minihack#95]
minihack.readthedocs.io is out of date. For example, search for `env._actions` in [the reward manager docs](https://minihack.readthedocs.io/en/latest/_modules/minihack/reward_manager.html), compared to [the reward manager file](https://github.com/facebookresearch/minihack/blob/main/minihack/reward_manager.py). It has been renamed to `env.actions` however the docs don't reflect this.

**Comment by samvelyan** [comment]
Thanks for the reminder. The documentation is now updated.
